### ISSUE TITLE
New strategy: ETag management

### ISSUE THREAD

**Issue by TimvdLippe** [GoogleChromeLabs/sw-toolbox#168]
I would like to propose a new strategy to be added which performs ETag header insertions.

The gist of the function is the following:

``` js
function insertETagFromResponse(request, response) {
  var headers = new Headers();
  // Copy all original headers
  for (var header in request.headers.keys()) {
    var value = request.headers[header];
    if (value) {
      headers.append(header, value);
    }
  }
  // Add previous ETag value to receive 304 response.
  headers.append('If-None-Match', response.headers.get('ETag'));
  return new Request(request.url, {
    method: 'GET',
    headers: headers,
    body: request.body,
    mode: request.mode === 'navigate' ? 'cors' : request.mode,
    credentials: request.credentials,
    cache: request.cache,
    redirect: request.redirect,
    referrer: request.referrer,
    integrity: request.integrity
  });
}

function retrieveETagFromCacheAndFetchRequest(request) {
  return caches.open(cacheName).then(function(cache) {
    return cache.match(request.url)
      .then(function(oldResponse) {
        var newRequest = request;
        if (oldResponse) {
          newRequest = insertETagFromResponse(request, oldResponse);
        }
        return fetch(newRequest).then(function(newResponse) {
          // Errors trigger the cache
          if (newResponse.status >= 304) {
            return oldResponse.clone();
          }
          // Update old cache entry with new result
          cache.put(request.url, newResponse.clone());
          return newResponse.clone();
        })
    })
}
```

Would you be interested in a pullrequest to add this strategy to the toolbox?

**Comment by NekR** [comment]
Why it's needed at all? Browsers already manage `Etag` and `Last-Modified` headers, do it doesn't make sense to duplicate the work.

**Comment by TimvdLippe** [comment]
That would surprise me, as I have not encountered the browsers taking care of this when communicating with the GitHub API. Anyways, we obtained major benefits for cross-session requests. E.g. use our application and insert requests in the cache. Restart your browser and use the old requests from the service-worker cache. Without this function, after a restart all requests would once again decrease the rate limit of GitHub even if it was in a matter of seconds.

As a result, we can use our application and restart all we want without having to pay the price. Our website is therefore a lot more usable for those users with a service-worker, resulting in progressive enhancement for the users that have the ability to.

**Comment by NekR** [comment]
You are saying so like browsers without SW don't use Etags. Have you measured benefit of method against pure browser cache without SW? I ask because, as you said, SW is just an enhancement over HTTP cache, so you don't need to reimplement it in SW again.

**Comment by TimvdLippe** [comment]
I don't recall the original issue and haven't gotten back to this issue. As I have not encountered it later, I probably made a mistake somewhere. Closing it for now. Thanks @NekR for responding so quick and sorry for not getting back to this.
