### ISSUE TITLE
Website for this repo has been 404

### ISSUE THREAD

**Issue by starkwang** [GoogleChromeLabs/sw-toolbox#273]
https://googlechrome.github.io/sw-toolbox/ has became 404 due to the change of the team name.
https://googlechromelabs.github.io/sw-toolbox/ is valid but the resources inside is 404.

**Comment by jeffposnick** [comment]
Thanks for pointing that out—I've done a [redeploy of the docs](https://github.com/GoogleChromeLabs/sw-toolbox/commit/e60a1eccf43dfb856d5508e7a5456b2b81161dbd) following the organization move, and that appears to have corrected the various internal links. Please let me know if you still something amiss.
