### ISSUE TITLE
Release 3.6.1 to NPM

### ISSUE THREAD

**Issue by urbany** [GoogleChromeLabs/sw-toolbox#276]
Latest in the repository is 3.6.1, but on [NPM it is still on 3.6.0](https://www.npmjs.com/package/sw-toolbox)

Thanks in advance!

**Comment by jeffposnick** [comment]
There are no code changes in between `3.6.0` and `3.6.1`. It was just a commit/tag to make bower happy: https://github.com/GoogleChromeLabs/sw-toolbox/releases/tag/v3.6.1 and therefore isn't needed for `npm` usage.
