### ISSUE TITLE
Consider bumping `path-to-regexp`.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [GoogleChromeLabs/sw-toolbox#278]
The currently required version uses `is-array`, which is a polyfill for `Array.isArray`.  Bumping it to `path-to-regexp@2` makes that go away.  It's not a big deal, but it might be a good idea.  I have a branch ready if you'd like a PR.

**Comment by jeffposnick** [comment]
Generally speaking, we're not planning on additional releases of `sw-toolbox`, as the team's efforts are focused on Workbox: https://github.com/GoogleChromeLabs/sw-toolbox#what-does-this-mean-for-sw-toolbox

(Critical bugs or security issues are still being addressed.)
