### ISSUE TITLE
Notify people about Workbox ("The next version of sw-precache & sw-toolbox")

### ISSUE THREAD

**Issue by rejhgadellaa** [GoogleChromeLabs/sw-toolbox#281]
I just found out by accident that SW-Toolbox is basically deprecated and the "new version" is Workbox:
https://developers.google.com/web/tools/workbox/#get-started

Would be useful to mention this in the README and/or docs?

**Comment by jeffposnick** [comment]
It's called out at https://github.com/GoogleChromeLabs/sw-toolbox#support

We might get a bit more aggressive in the future about calling it out once a larger share of usage shifts.
